//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được trống.
        /// </summary>
        public static string DevMsg_EmptyCode {
            get {
                return ResourceManager.GetString("DevMsg_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được trống.
        /// </summary>
        public static string DevMsg_EmptyDepartment {
            get {
                return ResourceManager.GetString("DevMsg_EmptyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu chuyền vào trống hoặc chứa khoảng trắng.
        /// </summary>
        public static string DevMsg_EmptyInput {
            get {
                return ResourceManager.GetString("DevMsg_EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được trống.
        /// </summary>
        public static string DevMsg_EmptyName {
            get {
                return ResourceManager.GetString("DevMsg_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không đúng định dạng: bắt đầu bằng NV- và kết thúc bằng 5 số.
        /// </summary>
        public static string DevMsg_InvalidCode {
            get {
                return ResourceManager.GetString("DevMsg_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string DevMsg_InvalidEmail {
            get {
                return ResourceManager.GetString("DevMsg_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một thuộc tính có chứa kiểu dữ liệu không hợp lệ, kiểm tra những int hoặc guid.
        /// </summary>
        public static string DevMsg_InvalidInput {
            get {
                return ResourceManager.GetString("DevMsg_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chứa kí tự đặc biệt, số hoặc quá nhiều khoảng trắng.
        /// </summary>
        public static string DevMsg_InvalidName {
            get {
                return ResourceManager.GetString("DevMsg_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số có chứa kí tự đặc biệt, chữ cái hoặc khoảng trắng.
        /// </summary>
        public static string DevMsg_InvalidNumber {
            get {
                return ResourceManager.GetString("DevMsg_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi truyền vào có thể gây ra thay đổi trong database.
        /// </summary>
        public static string DevMsg_InvalidString {
            get {
                return ResourceManager.GetString("DevMsg_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra phía back-end.
        /// </summary>
        public static string DevMsg_ServerError {
            get {
                return ResourceManager.GetString("DevMsg_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string UserMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được trống.
        /// </summary>
        public static string UserMsg_EmptyCode {
            get {
                return ResourceManager.GetString("UserMsg_EmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được trống.
        /// </summary>
        public static string UserMsg_EmptyDepartment {
            get {
                return ResourceManager.GetString("UserMsg_EmptyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trống.
        /// </summary>
        public static string UserMsg_EmptyInput {
            get {
                return ResourceManager.GetString("UserMsg_EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được trống.
        /// </summary>
        public static string UserMsg_EmptyName {
            get {
                return ResourceManager.GetString("UserMsg_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không đúng định dạng: bắt đầu bằng NV- và kết thúc bằng 5 số.
        /// </summary>
        public static string UserMsg_InvalidCode {
            get {
                return ResourceManager.GetString("UserMsg_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string UserMsg_InvalidEmail {
            get {
                return ResourceManager.GetString("UserMsg_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không hợp lệ.
        /// </summary>
        public static string UserMsg_InvalidName {
            get {
                return ResourceManager.GetString("UserMsg_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng số.
        /// </summary>
        public static string UserMsg_InvalidNumber {
            get {
                return ResourceManager.GetString("UserMsg_InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi truyền vào có chứa kí tự đặc biệt.
        /// </summary>
        public static string UserMsg_InvalidString {
            get {
                return ResourceManager.GetString("UserMsg_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng thử lại sau ít phút.
        /// </summary>
        public static string UserMsg_ServerError {
            get {
                return ResourceManager.GetString("UserMsg_ServerError", resourceCulture);
            }
        }
    }
}
